### ISSUE TITLE
feature : mumble-moderator

### ISSUE THREAD

**Issue by azlux** [sudoforge/docker-images#103]
Hi,

I see your image, and I want to propose you an improvement:
What about a option to enable MUMO (MUmble-MOderator)

Official repo is here :  https://github.com/mumble-voip/mumo (some [help here](https://wiki.natenom.de/en/mumble/tools/mumo/mumo-installation) ).

Lot of mumble server use it to customize the server.

Azlux

**Comment by sudoforge** [comment]
Hey @azlux - thanks for the suggestion! I've got a busy few days, but I'll take a look at the MUMO project as soon as I have time (likely mid-to-late next week) and figure out how it can best fit into the mumble-server image's ecosystem.

**Comment by azlux** [comment]
Since a pull requests is done, I will close this issue

**Comment by sudoforge** [comment]
Actually I think it makes sense to keep the issue open until I have a chance to merge the PR.

**Comment by sudoforge** [comment]
Closed as the mumo image is merged into https://github.com/mumble-voip/mumo
