### ISSUE TITLE
not possible to specify ssl certs

### ISSUE THREAD

**Issue by abate** [sudoforge/docker-images#89]
I'm happy of this image. really well done. I've one small problem though.
Since I've my certs in a separate docker volume, it's kinda complicated to 
share them with the miumur container since the position of the certs is
hardcoded in the entrypoint.sh

```
    SSL_CERTFILE=/data/cert.pem
    SSL_KEYFILE=/data/key.pem
    SSL_CAFILE=/data/intermediate.pem
    SSL_DHFILE=/data/dh.pem
```
Can you expose these variables instead (maybe leaving the same default ) ?

Ideally I'd like to specify 
`SSL_CERTFILE=/data/certs/servername.pem` as env var
and add `-v mycerts:/data/certs` when I run the image

Something along these lines : 
```
      SSL_CERTFILE=${MUMBLE_CERTFILE:-/data/cert.pem} 
      SSL_KEYFILE=${MUMBLE_KEYFILE:-/data/key.pem}
      SSL_CAFILE=${MUMBLE_CAFILE:-/data/intermediate.pem} 
      SSL_DHFILE=${MUMBLE_DHFILE:-/data/dh.pem}
```

**Comment by sudoforge** [comment]
Hey! Glad to hear it's helpful, and thank you for raising this issue. I'll take a look at a better way of abstracting the method of providing certs.

CC @SISheogorath

**Comment by SISheogorath** [comment]
Hehe, long time no se, I think the suggestion makes sense, we could even go crazy and use:

```
SSL_CERTFILE=${SSL_CERTFILE:-/data/cert.pem} 
SSL_KEYFILE=${SSL_KEYFILE:-/data/key.pem}
SSL_CAFILE=${SSL_CAFILE:-/data/intermediate.pem} 
SSL_DHFILE=${SSL_DHFILE:-/data/dh.pem}
```

(Of course one could also use `MUMBLE_` instead of `SSL_` here, which I might prefer)

But all in all, I think it makes sense.
