### ISSUE TITLE
Thoughts on exec'ing Murmur process

### ISSUE THREAD

**Issue by KetchupBomb** [sudoforge/docker-images#98]
I currently have a Cron job which blindly restarts my Murmur container the first Monday of each month in order to reload LetsEncrypt certificates.

Now that Murmur 1.3 is provided with support for `SIGUSR1` to live-reload certificate information, I'd like to perform something simple like:

```
$ docker kill --signal SIGUSR1 mumble-server
```

Which will send the specified signal to PID 1. However, this image has the `docker-entrypoint.sh` as the first process which forks off `murmur`, having no effect.

Are you open to changing:

https://github.com/sudoforge/docker-images/blob/b15e058596f6dc4ac00217186841433766ccb5ea/mumble-server/docker-entrypoint.sh#L106

to:

```
exec /opt/murmur/murmur.x86 -fg -ini "${CONFIGFILE}"
```

---

Another option is to `trap` `SIGUSR1` in `docker-entrypoint.sh` and it sending `kill -s SIGUSR1 $(pgrep murmur)` (or whatever other method is desired).

**Comment by sudoforge** [comment]
Great suggestion! In my opinion, `exec`-ing would be a bit cleaner. I sent up a patch to try this out (I don't foresee any issues).
